using System.Globalization;
using System.Security;
using System.Text;

namespace Plaitway.Localization;

/// <summary>
/// Writes <c>UiText</c>, the class the code reads its strings from: one property per string and one method per
/// string that takes arguments. A string that is not in the catalogs is a compile error at the place that uses it.
/// </summary>
internal static class UiTextWriter
{
    private const string Indent = "    ";

    /// <summary>The source file, in <paramref name="namespaceName"/>.</summary>
    public static string Render(IEnumerable<LocalizedString> strings, string namespaceName)
    {
        var all = strings.ToList();
        var source = new StringBuilder();
        source.Append("// <auto-generated>\n");
        source.Append("// Generated by Plaitway.Localization from the string catalogs. Do not edit.\n");
        source.Append("// </auto-generated>\n");
        source.Append("#nullable enable\n\n");
        source.Append(CultureInfo.InvariantCulture, $"namespace {namespaceName};\n\n");
        source.Append("/// <summary>Every string of the interface, in the language of the localizer it is made with.</summary>\n");
        source.Append("public sealed class UiText(ILocalizer localizer)\n{\n");
        source.Append(Indent).Append("/// <summary>The culture of the strings, for the numbers and dates that are put next to them.</summary>\n");
        source.Append(Indent).Append("public System.Globalization.CultureInfo Culture => localizer.Culture;\n\n");
        source.Append(Indent).Append("/// <summary>The resource id of every string.</summary>\n");
        source.Append(Indent).Append("public static IReadOnlyList<string> Ids { get; } =\n").Append(Indent).Append("[\n");
        foreach (var text in all)
        {
            source.Append(Indent).Append(Indent).Append(CultureInfo.InvariantCulture, $"\"{text.Id}\",\n");
        }

        source.Append(Indent).Append("];\n");
        foreach (var text in all)
        {
            source.Append('\n');
            AppendMember(source, text);
        }

        source.Append('\n');
        source.Append(Indent).Append("private string Format(string id, params object[] arguments) =>\n");
        source.Append(Indent).Append(Indent).Append("string.Format(localizer.Culture, localizer.Resolve(id), arguments);\n");
        source.Append("}\n");
        return source.ToString();
    }

    private static void AppendMember(StringBuilder source, LocalizedString text)
    {
        source.Append(Indent).Append(CultureInfo.InvariantCulture, $"/// <summary>{SecurityElement.Escape(text.Key)}</summary>\n");
        if (text.Specifiers.Count == 0)
        {
            source.Append(Indent).Append(CultureInfo.InvariantCulture, $"public string {text.Id} => localizer.Resolve(\"{text.Id}\");\n");
            return;
        }

        var parameters = text.Specifiers.Select(specifier => ParameterOf(specifier, text.Specifiers.Count)).ToList();
        var declaration = string.Join(", ", parameters.Select(parameter => $"{parameter.Type} {parameter.Name}"));
        var names = string.Join(", ", parameters.Select(parameter => parameter.Name));
        source.Append(Indent).Append(CultureInfo.InvariantCulture, $"public string {text.Id}({declaration}) => Format(\"{text.Id}\", {names});\n");
    }

    private static (string Type, string Name) ParameterOf(FormatSpecifier specifier, int count)
    {
        var (type, name) = specifier.Kind == ArgumentKind.Text ? ("string", "value") : ("long", "number");
        return (type, count == 1 ? name : name + (specifier.Index + 1).ToString(CultureInfo.InvariantCulture));
    }
}
