"""Every string of the UI, as typed accessors. Generated by tools/localize.py: do not edit.

The strings are those of the macOS app (macos/Sources/PlaitwayMenuBar/Resources/Localizable.xcstrings)
that have a role on Linux, and linux/Resources/Linux.xcstrings.
"""

from __future__ import annotations

# language -> accessor -> template; {0}, {1} are the arguments of the accessor.
_TABLES: dict[str, dict[str, str]] = {
    'en': {
        'about_plaitway': 'About Plaitway',
        'addresses': 'Addresses',
        'administrator_required': 'Administrator required',
        'all_domains': 'All domains',
        'all_levels': 'All levels',
        'app_version': 'App version',
        'applies_at_next_connection': 'Applies at next connection',
        'attention': 'Attention',
        'auto': 'Auto',
        'auto_connect': 'Auto-connect',
        'awaiting_credentials': 'Awaiting credentials',
        'blocked_by_local_network': 'Blocked by local network',
        'bypass': 'Bypass',
        'cancel': 'Cancel',
        'cannot_read': 'Cannot read {0}: {1}',
        'close': 'Close',
        'configuration': 'Configuration',
        'connect': 'Connect',
        'connect_failed': 'Connect failed',
        'connected': 'Connected',
        'connected_count': 'Connected: {0}',
        'connected_profiles_disconnect': 'Connected profiles disconnect.',
        'connected_profiles_stay_connected': 'Connected profiles stay connected.',
        'connecting': 'Connecting',
        'console_user_only': 'Only the console user and administrators can use the helper.',
        'copy': 'Copy',
        'copy_report': 'Copy Report',
        'credentials': 'Credentials',
        'credentials_file_invalid': 'File for auth-user-pass holds no user name and password: {0}',
        'credentials_not_saved': 'Credentials not saved',
        'credentials_rejected': 'Credentials rejected',
        'default_gateway': 'Default gateway',
        'default_gateway_ipv6': 'Default gateway IPv6',
        'default_route': 'Default route',
        'delete': 'Delete',
        'delete_failed': 'Delete failed',
        'delete_profile': 'Delete Profile…',
        'delete_profile_message': 'The profile and its saved credentials are removed.',
        'delete_profile_title': 'Delete “{0}”?',
        'diagnostics': 'Diagnostics',
        'disconnect': 'Disconnect',
        'disconnect_all': 'Disconnect All',
        'disconnect_all_and_quit': 'Disconnect All and Quit',
        'disconnected': 'Disconnected',
        'disconnecting': 'Disconnecting',
        'dns': 'DNS',
        'errors_only': 'Errors only',
        'ethernet': 'Ethernet',
        'exclude_private_ips': 'Exclude private IPs',
        'failed': 'Failed',
        'file_holds_no_key': 'File for {0} holds no certificate or key: {1}',
        'file_not_found': 'File for {0} not found: {1}',
        'file_outside_folder': "File for {0} is outside the profile's folder: {1}",
        'file_too_large': 'File too large: {0}',
        'full_tunnel': 'Full tunnel',
        'helper': 'Helper',
        'helper_failed': 'Helper failed',
        'helper_log': 'Helper log',
        'helper_log_location': 'Helper log: {0}',
        'helper_not_installed': 'Helper not installed',
        'helper_not_running': 'Helper not running',
        'helper_not_trusted': 'Helper not trusted',
        'helper_out_of_date': 'Helper out of date',
        'helper_unavailable': 'Helper unavailable',
        'helper_version': 'Helper version',
        'hide_secrets': 'Hide Secrets',
        'import_failed': 'Import failed',
        'import_label': 'Import',
        'import_profile': 'Import Profile…',
        'info_and_above': 'Info and above',
        'install_the_package': 'Install the plaitway package.',
        'installed': 'Installed',
        'installed_by_plaitway': 'Installed by Plaitway',
        'interface': 'Interface',
        'interfaces': 'Interfaces',
        'key_passphrase': 'Key passphrase',
        'last_change': 'Last change',
        'latest': 'Latest',
        'launch_at_login': 'Launch at Login',
        'launch_at_login_failed': 'Launch at Login failed',
        'level': 'Level',
        'limited': 'Limited',
        'line_number': 'Line {0}',
        'logs': 'Logs',
        'main_menu': 'Main Menu',
        'move_down': 'Move Down',
        'move_up': 'Move Up',
        'name': 'Name',
        'network': 'Network',
        'no_log_lines': 'No Log Lines',
        'no_profiles': 'No Profiles',
        'no_routes': 'No Routes',
        'none': 'None',
        'not_a_text_file': 'Not a text file: {0}',
        'not_connected': 'Not connected',
        'not_installed': 'Not installed',
        'on_demand': 'On demand',
        'on_demand_footer': 'Connects on the checked networks and disconnects on any other.',
        'open_plaitway': 'Open Plaitway',
        'open_settings': 'Settings…',
        'overview': 'Overview',
        'passphrase': 'Passphrase',
        'password': 'Password',
        'pending': 'Pending',
        'permission_denied': 'Permission denied',
        'priority': 'Priority',
        'priority_hint': 'A higher priority wins overlapping routes and DNS domains.',
        'private_ranges_hint': 'Private address ranges stay outside the tunnel.',
        'privileges': 'Privileges',
        'problem': 'Problem',
        'profile_not_found': 'Profile not found',
        'profiles': 'Profiles',
        'public_key': 'Public key',
        'quit': 'Quit',
        'quit_plaitway': 'Quit Plaitway',
        'quit_plaitway_title': 'Quit Plaitway?',
        'quit_with_unsaved_changes': 'Quit with unsaved changes?',
        'rate_per_second': '{0}/s',
        'received': 'Received',
        'recent_changes': 'Recent changes',
        'reconnecting': 'Reconnecting',
        'remote': 'Remote',
        'remove': 'Remove',
        'remove_failed': 'Remove failed',
        'remove_route_title': 'Remove route {0}?',
        'remove_saved_credentials': 'Remove Saved Credentials',
        'reorder_failed': 'Reorder failed',
        'resolver_entries': 'Resolver entries',
        'restart': 'Restart',
        'restart_helper': 'Restart Helper',
        'restart_helper_title': 'Restart helper?',
        'resync': 'Resync',
        'resync_failed': 'Resync failed',
        'retry': 'Retry',
        'revert': 'Revert',
        'routes': 'Routes',
        'routes_and_dns': 'Routes and DNS',
        'routes_not_in_effect': 'Routes not in effect',
        'running': 'Running',
        'running_not_answering': 'Running, not answering.',
        'save': 'Save',
        'save_and_reconnect': 'Save and Reconnect',
        'save_failed': 'Save failed',
        'search_logs': 'Search Logs',
        'secret_appears_more_than_once': 'Secret {0} appears more than once',
        'secret_service_unavailable': 'Secret Service unavailable',
        'sent': 'Sent',
        'settings': 'Settings',
        'shadowed': 'Shadowed',
        'shadowed_by': 'Shadowed by {0}',
        'show': 'Show',
        'show_secrets': 'Show Secrets',
        'show_tray_icon': 'Show Tray Icon',
        'split_tunnel': 'Split tunnel',
        'stale_routes': 'Stale routes',
        'start_development_daemon': 'Start plaitwayd, then set PLAITWAY_DEV=1 and PLAITWAY_SOCKET.',
        'start_helper': 'Start Helper',
        'status': 'Status',
        'stopped': 'Stopped',
        'tunnel': 'Tunnel',
        'tunnel_mode': 'Tunnel mode',
        'unavailable': 'Unavailable',
        'unknown': 'Unknown',
        'unsaved_changes_message': "Changes to a profile's text are not saved.",
        'uptime': 'Uptime',
        'username': 'Username',
        'warnings_and_errors': 'Warnings and errors',
        'wi_fi': 'Wi-Fi',
    },
    'zh-Hant': {
        'about_plaitway': '關於 Plaitway',
        'addresses': '位址',
        'administrator_required': '需要管理員權限',
        'all_domains': '所有網域',
        'all_levels': '所有層級',
        'app_version': 'App 版本',
        'applies_at_next_connection': '下次連線時生效',
        'attention': '需要注意',
        'auto': '自動',
        'auto_connect': '自動連線',
        'awaiting_credentials': '等待登入資訊',
        'blocked_by_local_network': '被本機網路阻擋',
        'bypass': '旁路',
        'cancel': '取消',
        'cannot_read': '無法讀取 {0}：{1}',
        'close': '關閉',
        'configuration': '組態',
        'connect': '連線',
        'connect_failed': '連線失敗',
        'connected': '已連線',
        'connected_count': '已連線：{0}',
        'connected_profiles_disconnect': '已連線的設定檔將中斷連線。',
        'connected_profiles_stay_connected': '已連線的設定檔會保持連線。',
        'connecting': '連線中',
        'console_user_only': '只有主控台使用者與管理員可以使用輔助程式。',
        'copy': '拷貝',
        'copy_report': '拷貝報告',
        'credentials': '登入資訊',
        'credentials_file_invalid': 'auth-user-pass 所指的檔案不含使用者名稱與密碼：{0}',
        'credentials_not_saved': '登入資訊未儲存',
        'credentials_rejected': '登入資訊遭拒',
        'default_gateway': '預設閘道',
        'default_gateway_ipv6': 'IPv6 預設閘道',
        'default_route': '預設路由',
        'delete': '刪除',
        'delete_failed': '刪除失敗',
        'delete_profile': '刪除設定檔…',
        'delete_profile_message': '設定檔及其已儲存的登入資訊將被移除。',
        'delete_profile_title': '刪除「{0}」？',
        'diagnostics': '診斷',
        'disconnect': '中斷連線',
        'disconnect_all': '全部中斷連線',
        'disconnect_all_and_quit': '全部中斷連線並結束',
        'disconnected': '未連線',
        'disconnecting': '中斷連線中',
        'dns': 'DNS',
        'errors_only': '僅錯誤',
        'ethernet': '乙太網路',
        'exclude_private_ips': '排除私有 IP',
        'failed': '失敗',
        'file_holds_no_key': '{0} 所指的檔案不含憑證或金鑰：{1}',
        'file_not_found': '找不到 {0} 所指的檔案：{1}',
        'file_outside_folder': '{0} 所指的檔案不在設定檔所在的資料夾內：{1}',
        'file_too_large': '檔案過大：{0}',
        'full_tunnel': '完整通道',
        'helper': '輔助程式',
        'helper_failed': '輔助程式失敗',
        'helper_log': '輔助程式記錄',
        'helper_log_location': '輔助程式記錄：{0}',
        'helper_not_installed': '未安裝輔助程式',
        'helper_not_running': '輔助程式未執行',
        'helper_not_trusted': '輔助程式不受信任',
        'helper_out_of_date': '輔助程式版本過舊',
        'helper_unavailable': '輔助程式無法使用',
        'helper_version': '輔助程式版本',
        'hide_secrets': '隱藏機密',
        'import_failed': '匯入失敗',
        'import_label': '匯入',
        'import_profile': '匯入設定檔…',
        'info_and_above': '資訊以上',
        'install_the_package': '請安裝 plaitway 套件。',
        'installed': '已安裝',
        'installed_by_plaitway': '由 Plaitway 安裝',
        'interface': '介面',
        'interfaces': '網路介面',
        'key_passphrase': '金鑰通行密語',
        'last_change': '上次變更',
        'latest': '最新',
        'launch_at_login': '登入時啟動',
        'launch_at_login_failed': '登入時啟動失敗',
        'level': '層級',
        'limited': '受限',
        'line_number': '第 {0} 行',
        'logs': '記錄',
        'main_menu': '主選單',
        'move_down': '下移',
        'move_up': '上移',
        'name': '名稱',
        'network': '網路',
        'no_log_lines': '沒有記錄',
        'no_profiles': '沒有設定檔',
        'no_routes': '沒有路由',
        'none': '無',
        'not_a_text_file': '不是文字檔：{0}',
        'not_connected': '未連線',
        'not_installed': '未安裝',
        'on_demand': '隨選連線',
        'on_demand_footer': '在勾選的網路上連線，在其他網路上中斷連線。',
        'open_plaitway': '打開 Plaitway',
        'open_settings': '設定…',
        'overview': '概覽',
        'passphrase': '通行密語',
        'password': '密碼',
        'pending': '等待中',
        'permission_denied': '權限不足',
        'priority': '優先順序',
        'priority_hint': '優先順序較高者取得重疊的路由與 DNS 網域。',
        'private_ranges_hint': '私有位址範圍不經過通道。',
        'privileges': '權限',
        'problem': '發生問題',
        'profile_not_found': '找不到設定檔',
        'profiles': '設定檔',
        'public_key': '公開金鑰',
        'quit': '結束',
        'quit_plaitway': '結束 Plaitway',
        'quit_plaitway_title': '結束 Plaitway？',
        'quit_with_unsaved_changes': '要在尚未儲存變更時結束嗎？',
        'rate_per_second': '{0}/秒',
        'received': '已接收',
        'recent_changes': '最近變更',
        'reconnecting': '重新連線中',
        'remote': '遠端',
        'remove': '移除',
        'remove_failed': '移除失敗',
        'remove_route_title': '移除路由 {0}？',
        'remove_saved_credentials': '移除已儲存的登入資訊',
        'reorder_failed': '重新排序失敗',
        'resolver_entries': '解析器項目',
        'restart': '重新啟動',
        'restart_helper': '重新啟動輔助程式',
        'restart_helper_title': '重新啟動輔助程式？',
        'resync': '重新同步',
        'resync_failed': '重新同步失敗',
        'retry': '重試',
        'revert': '還原',
        'routes': '路由',
        'routes_and_dns': '路由與 DNS',
        'routes_not_in_effect': '未生效的路由',
        'running': '執行中',
        'running_not_answering': '執行中，但沒有回應。',
        'save': '儲存',
        'save_and_reconnect': '儲存並重新連線',
        'save_failed': '儲存失敗',
        'search_logs': '搜尋記錄',
        'secret_appears_more_than_once': '機密 {0} 出現了不只一次',
        'secret_service_unavailable': '無法使用 Secret Service',
        'sent': '已傳送',
        'settings': '設定',
        'shadowed': '被遮蔽',
        'shadowed_by': '被 {0} 遮蔽',
        'show': '顯示',
        'show_secrets': '顯示機密',
        'show_tray_icon': '顯示系統匣圖示',
        'split_tunnel': '分割通道',
        'stale_routes': '過時路由',
        'start_development_daemon': '請啟動 plaitwayd，並設定 PLAITWAY_DEV=1 與 PLAITWAY_SOCKET。',
        'start_helper': '啟動輔助程式',
        'status': '狀態',
        'stopped': '已停止',
        'tunnel': '通道',
        'tunnel_mode': '通道模式',
        'unavailable': '無法使用',
        'unknown': '未知',
        'unsaved_changes_message': '設定檔內容的變更尚未儲存。',
        'uptime': '連線時間',
        'username': '使用者名稱',
        'warnings_and_errors': '警告與錯誤',
        'wi_fi': 'Wi-Fi',
    },
}

LANGUAGES = ('en', 'zh-Hant')


class Strings:
    """The strings in one language. An unknown language reads as English."""

    def __init__(self, language: str = "en") -> None:
        self.language = language if language in _TABLES else "en"
        self._table = _TABLES[self.language]

    # macOS: About Plaitway
    @property
    def about_plaitway(self) -> str:
        return self._table['about_plaitway']

    # macOS: Addresses
    @property
    def addresses(self) -> str:
        return self._table['addresses']

    # macOS: Administrator required
    @property
    def administrator_required(self) -> str:
        return self._table['administrator_required']

    # macOS: All domains
    @property
    def all_domains(self) -> str:
        return self._table['all_domains']

    # macOS: All levels
    @property
    def all_levels(self) -> str:
        return self._table['all_levels']

    # macOS: App version
    @property
    def app_version(self) -> str:
        return self._table['app_version']

    # macOS: Applies at next connection
    @property
    def applies_at_next_connection(self) -> str:
        return self._table['applies_at_next_connection']

    # macOS: Attention
    @property
    def attention(self) -> str:
        return self._table['attention']

    # macOS: Auto
    @property
    def auto(self) -> str:
        return self._table['auto']

    # macOS: Auto-connect
    @property
    def auto_connect(self) -> str:
        return self._table['auto_connect']

    # macOS: Awaiting credentials
    @property
    def awaiting_credentials(self) -> str:
        return self._table['awaiting_credentials']

    # macOS: Blocked by local network
    @property
    def blocked_by_local_network(self) -> str:
        return self._table['blocked_by_local_network']

    # macOS: Bypass
    @property
    def bypass(self) -> str:
        return self._table['bypass']

    # macOS: Cancel
    @property
    def cancel(self) -> str:
        return self._table['cancel']

    # macOS: Cannot read %@: %@
    def cannot_read(self, path: str, reason: str) -> str:
        return self._table['cannot_read'].format(path, reason)

    # macOS: Close
    @property
    def close(self) -> str:
        return self._table['close']

    # macOS: Configuration
    @property
    def configuration(self) -> str:
        return self._table['configuration']

    # macOS: Connect
    @property
    def connect(self) -> str:
        return self._table['connect']

    # macOS: Connect failed
    @property
    def connect_failed(self) -> str:
        return self._table['connect_failed']

    # macOS: Connected
    @property
    def connected(self) -> str:
        return self._table['connected']

    # macOS: Connected: %lld
    def connected_count(self, count: int) -> str:
        return self._table['connected_count'].format(count)

    # macOS: Connected profiles disconnect.
    @property
    def connected_profiles_disconnect(self) -> str:
        return self._table['connected_profiles_disconnect']

    # macOS: Connected profiles stay connected.
    @property
    def connected_profiles_stay_connected(self) -> str:
        return self._table['connected_profiles_stay_connected']

    # macOS: Connecting
    @property
    def connecting(self) -> str:
        return self._table['connecting']

    # Linux: Only the console user and administrators can use the helper.
    @property
    def console_user_only(self) -> str:
        return self._table['console_user_only']

    # macOS: Copy
    @property
    def copy(self) -> str:
        return self._table['copy']

    # macOS: Copy Report
    @property
    def copy_report(self) -> str:
        return self._table['copy_report']

    # macOS: Credentials
    @property
    def credentials(self) -> str:
        return self._table['credentials']

    # macOS: File for auth-user-pass holds no user name and password: %@
    def credentials_file_invalid(self, path: str) -> str:
        return self._table['credentials_file_invalid'].format(path)

    # Linux: Credentials not saved
    @property
    def credentials_not_saved(self) -> str:
        return self._table['credentials_not_saved']

    # macOS: Credentials rejected
    @property
    def credentials_rejected(self) -> str:
        return self._table['credentials_rejected']

    # macOS: Default gateway
    @property
    def default_gateway(self) -> str:
        return self._table['default_gateway']

    # macOS: Default gateway IPv6
    @property
    def default_gateway_ipv6(self) -> str:
        return self._table['default_gateway_ipv6']

    # macOS: Default route
    @property
    def default_route(self) -> str:
        return self._table['default_route']

    # macOS: Delete
    @property
    def delete(self) -> str:
        return self._table['delete']

    # macOS: Delete failed
    @property
    def delete_failed(self) -> str:
        return self._table['delete_failed']

    # macOS: Delete Profile…
    @property
    def delete_profile(self) -> str:
        return self._table['delete_profile']

    # macOS: The profile and its saved credentials are removed.
    @property
    def delete_profile_message(self) -> str:
        return self._table['delete_profile_message']

    # macOS: Delete “%@”?
    def delete_profile_title(self, name: str) -> str:
        return self._table['delete_profile_title'].format(name)

    # macOS: Diagnostics
    @property
    def diagnostics(self) -> str:
        return self._table['diagnostics']

    # macOS: Disconnect
    @property
    def disconnect(self) -> str:
        return self._table['disconnect']

    # macOS: Disconnect All
    @property
    def disconnect_all(self) -> str:
        return self._table['disconnect_all']

    # macOS: Disconnect All and Quit
    @property
    def disconnect_all_and_quit(self) -> str:
        return self._table['disconnect_all_and_quit']

    # macOS: Disconnected
    @property
    def disconnected(self) -> str:
        return self._table['disconnected']

    # macOS: Disconnecting
    @property
    def disconnecting(self) -> str:
        return self._table['disconnecting']

    # macOS: DNS
    @property
    def dns(self) -> str:
        return self._table['dns']

    # macOS: Errors only
    @property
    def errors_only(self) -> str:
        return self._table['errors_only']

    # macOS: Ethernet
    @property
    def ethernet(self) -> str:
        return self._table['ethernet']

    # macOS: Exclude private IPs
    @property
    def exclude_private_ips(self) -> str:
        return self._table['exclude_private_ips']

    # macOS: Failed
    @property
    def failed(self) -> str:
        return self._table['failed']

    # macOS: File for %@ holds no certificate or key: %@
    def file_holds_no_key(self, directive: str, path: str) -> str:
        return self._table['file_holds_no_key'].format(directive, path)

    # macOS: File for %@ not found: %@
    def file_not_found(self, directive: str, path: str) -> str:
        return self._table['file_not_found'].format(directive, path)

    # macOS: File for %@ is outside the profile's folder: %@
    def file_outside_folder(self, directive: str, path: str) -> str:
        return self._table['file_outside_folder'].format(directive, path)

    # macOS: File too large: %@
    def file_too_large(self, path: str) -> str:
        return self._table['file_too_large'].format(path)

    # macOS: Full tunnel
    @property
    def full_tunnel(self) -> str:
        return self._table['full_tunnel']

    # macOS: Helper
    @property
    def helper(self) -> str:
        return self._table['helper']

    # macOS: Helper failed
    @property
    def helper_failed(self) -> str:
        return self._table['helper_failed']

    # macOS: Helper log
    @property
    def helper_log(self) -> str:
        return self._table['helper_log']

    # macOS: Helper log: %@
    def helper_log_location(self, location: str) -> str:
        return self._table['helper_log_location'].format(location)

    # macOS: Helper not installed
    @property
    def helper_not_installed(self) -> str:
        return self._table['helper_not_installed']

    # Linux: Helper not running
    @property
    def helper_not_running(self) -> str:
        return self._table['helper_not_running']

    # Linux: Helper not trusted
    @property
    def helper_not_trusted(self) -> str:
        return self._table['helper_not_trusted']

    # macOS: Helper out of date
    @property
    def helper_out_of_date(self) -> str:
        return self._table['helper_out_of_date']

    # macOS: Helper unavailable
    @property
    def helper_unavailable(self) -> str:
        return self._table['helper_unavailable']

    # macOS: Helper version
    @property
    def helper_version(self) -> str:
        return self._table['helper_version']

    # macOS: Hide Secrets
    @property
    def hide_secrets(self) -> str:
        return self._table['hide_secrets']

    # macOS: Import failed
    @property
    def import_failed(self) -> str:
        return self._table['import_failed']

    # macOS: Import
    @property
    def import_label(self) -> str:
        return self._table['import_label']

    # macOS: Import Profile…
    @property
    def import_profile(self) -> str:
        return self._table['import_profile']

    # macOS: Info and above
    @property
    def info_and_above(self) -> str:
        return self._table['info_and_above']

    # Linux: Install the plaitway package.
    @property
    def install_the_package(self) -> str:
        return self._table['install_the_package']

    # macOS: Installed
    @property
    def installed(self) -> str:
        return self._table['installed']

    # macOS: Installed by Plaitway
    @property
    def installed_by_plaitway(self) -> str:
        return self._table['installed_by_plaitway']

    # macOS: Interface
    @property
    def interface(self) -> str:
        return self._table['interface']

    # macOS: Interfaces
    @property
    def interfaces(self) -> str:
        return self._table['interfaces']

    # macOS: Key passphrase
    @property
    def key_passphrase(self) -> str:
        return self._table['key_passphrase']

    # macOS: Last change
    @property
    def last_change(self) -> str:
        return self._table['last_change']

    # macOS: Latest
    @property
    def latest(self) -> str:
        return self._table['latest']

    # macOS: Launch at Login
    @property
    def launch_at_login(self) -> str:
        return self._table['launch_at_login']

    # macOS: Launch at Login failed
    @property
    def launch_at_login_failed(self) -> str:
        return self._table['launch_at_login_failed']

    # macOS: Level
    @property
    def level(self) -> str:
        return self._table['level']

    # macOS: Limited
    @property
    def limited(self) -> str:
        return self._table['limited']

    # macOS: Line %lld
    def line_number(self, line: int) -> str:
        return self._table['line_number'].format(line)

    # macOS: Logs
    @property
    def logs(self) -> str:
        return self._table['logs']

    # Linux: Main Menu
    @property
    def main_menu(self) -> str:
        return self._table['main_menu']

    # macOS: Move Down
    @property
    def move_down(self) -> str:
        return self._table['move_down']

    # macOS: Move Up
    @property
    def move_up(self) -> str:
        return self._table['move_up']

    # macOS: Name
    @property
    def name(self) -> str:
        return self._table['name']

    # macOS: Network
    @property
    def network(self) -> str:
        return self._table['network']

    # macOS: No Log Lines
    @property
    def no_log_lines(self) -> str:
        return self._table['no_log_lines']

    # macOS: No Profiles
    @property
    def no_profiles(self) -> str:
        return self._table['no_profiles']

    # macOS: No Routes
    @property
    def no_routes(self) -> str:
        return self._table['no_routes']

    # macOS: None
    @property
    def none(self) -> str:
        return self._table['none']

    # macOS: Not a text file: %@
    def not_a_text_file(self, path: str) -> str:
        return self._table['not_a_text_file'].format(path)

    # macOS: Not connected
    @property
    def not_connected(self) -> str:
        return self._table['not_connected']

    # macOS: Not installed
    @property
    def not_installed(self) -> str:
        return self._table['not_installed']

    # macOS: On demand
    @property
    def on_demand(self) -> str:
        return self._table['on_demand']

    # macOS: Connects on the checked networks and disconnects on any other.
    @property
    def on_demand_footer(self) -> str:
        return self._table['on_demand_footer']

    # macOS: Open Plaitway
    @property
    def open_plaitway(self) -> str:
        return self._table['open_plaitway']

    # macOS: Settings…
    @property
    def open_settings(self) -> str:
        return self._table['open_settings']

    # macOS: Overview
    @property
    def overview(self) -> str:
        return self._table['overview']

    # macOS: Passphrase
    @property
    def passphrase(self) -> str:
        return self._table['passphrase']

    # macOS: Password
    @property
    def password(self) -> str:
        return self._table['password']

    # macOS: Pending
    @property
    def pending(self) -> str:
        return self._table['pending']

    # Linux: Permission denied
    @property
    def permission_denied(self) -> str:
        return self._table['permission_denied']

    # macOS: Priority
    @property
    def priority(self) -> str:
        return self._table['priority']

    # macOS: A higher priority wins overlapping routes and DNS domains.
    @property
    def priority_hint(self) -> str:
        return self._table['priority_hint']

    # macOS: Private address ranges stay outside the tunnel.
    @property
    def private_ranges_hint(self) -> str:
        return self._table['private_ranges_hint']

    # macOS: Privileges
    @property
    def privileges(self) -> str:
        return self._table['privileges']

    # macOS: Problem
    @property
    def problem(self) -> str:
        return self._table['problem']

    # macOS: Profile not found
    @property
    def profile_not_found(self) -> str:
        return self._table['profile_not_found']

    # macOS: Profiles
    @property
    def profiles(self) -> str:
        return self._table['profiles']

    # macOS: Public key
    @property
    def public_key(self) -> str:
        return self._table['public_key']

    # macOS: Quit
    @property
    def quit(self) -> str:
        return self._table['quit']

    # macOS: Quit Plaitway
    @property
    def quit_plaitway(self) -> str:
        return self._table['quit_plaitway']

    # macOS: Quit Plaitway?
    @property
    def quit_plaitway_title(self) -> str:
        return self._table['quit_plaitway_title']

    # macOS: Quit with unsaved changes?
    @property
    def quit_with_unsaved_changes(self) -> str:
        return self._table['quit_with_unsaved_changes']

    # macOS: %@/s
    def rate_per_second(self, amount: str) -> str:
        return self._table['rate_per_second'].format(amount)

    # macOS: Received
    @property
    def received(self) -> str:
        return self._table['received']

    # macOS: Recent changes
    @property
    def recent_changes(self) -> str:
        return self._table['recent_changes']

    # macOS: Reconnecting
    @property
    def reconnecting(self) -> str:
        return self._table['reconnecting']

    # macOS: Remote
    @property
    def remote(self) -> str:
        return self._table['remote']

    # macOS: Remove
    @property
    def remove(self) -> str:
        return self._table['remove']

    # macOS: Remove failed
    @property
    def remove_failed(self) -> str:
        return self._table['remove_failed']

    # macOS: Remove route %@?
    def remove_route_title(self, prefix: str) -> str:
        return self._table['remove_route_title'].format(prefix)

    # macOS: Remove Saved Credentials
    @property
    def remove_saved_credentials(self) -> str:
        return self._table['remove_saved_credentials']

    # macOS: Reorder failed
    @property
    def reorder_failed(self) -> str:
        return self._table['reorder_failed']

    # macOS: Resolver entries
    @property
    def resolver_entries(self) -> str:
        return self._table['resolver_entries']

    # Linux: Restart
    @property
    def restart(self) -> str:
        return self._table['restart']

    # Linux: Restart Helper
    @property
    def restart_helper(self) -> str:
        return self._table['restart_helper']

    # Linux: Restart helper?
    @property
    def restart_helper_title(self) -> str:
        return self._table['restart_helper_title']

    # macOS: Resync
    @property
    def resync(self) -> str:
        return self._table['resync']

    # macOS: Resync failed
    @property
    def resync_failed(self) -> str:
        return self._table['resync_failed']

    # macOS: Retry
    @property
    def retry(self) -> str:
        return self._table['retry']

    # macOS: Revert
    @property
    def revert(self) -> str:
        return self._table['revert']

    # macOS: Routes
    @property
    def routes(self) -> str:
        return self._table['routes']

    # macOS: Routes and DNS
    @property
    def routes_and_dns(self) -> str:
        return self._table['routes_and_dns']

    # macOS: Routes not in effect
    @property
    def routes_not_in_effect(self) -> str:
        return self._table['routes_not_in_effect']

    # Linux: Running
    @property
    def running(self) -> str:
        return self._table['running']

    # Linux: Running, not answering.
    @property
    def running_not_answering(self) -> str:
        return self._table['running_not_answering']

    # macOS: Save
    @property
    def save(self) -> str:
        return self._table['save']

    # macOS: Save and Reconnect
    @property
    def save_and_reconnect(self) -> str:
        return self._table['save_and_reconnect']

    # macOS: Save failed
    @property
    def save_failed(self) -> str:
        return self._table['save_failed']

    # macOS: Search Logs
    @property
    def search_logs(self) -> str:
        return self._table['search_logs']

    # macOS: Secret %lld appears more than once
    def secret_appears_more_than_once(self, number: int) -> str:
        return self._table['secret_appears_more_than_once'].format(number)

    # Linux: Secret Service unavailable
    @property
    def secret_service_unavailable(self) -> str:
        return self._table['secret_service_unavailable']

    # macOS: Sent
    @property
    def sent(self) -> str:
        return self._table['sent']

    # macOS: Settings
    @property
    def settings(self) -> str:
        return self._table['settings']

    # macOS: Shadowed
    @property
    def shadowed(self) -> str:
        return self._table['shadowed']

    # macOS: Shadowed by %@
    def shadowed_by(self, profile: str) -> str:
        return self._table['shadowed_by'].format(profile)

    # macOS: Show
    @property
    def show(self) -> str:
        return self._table['show']

    # macOS: Show Secrets
    @property
    def show_secrets(self) -> str:
        return self._table['show_secrets']

    # Linux: Show Tray Icon
    @property
    def show_tray_icon(self) -> str:
        return self._table['show_tray_icon']

    # macOS: Split tunnel
    @property
    def split_tunnel(self) -> str:
        return self._table['split_tunnel']

    # macOS: Stale routes
    @property
    def stale_routes(self) -> str:
        return self._table['stale_routes']

    # Linux: Start plaitwayd, then set PLAITWAY_DEV=1 and PLAITWAY_SOCKET.
    @property
    def start_development_daemon(self) -> str:
        return self._table['start_development_daemon']

    # Linux: Start Helper
    @property
    def start_helper(self) -> str:
        return self._table['start_helper']

    # macOS: Status
    @property
    def status(self) -> str:
        return self._table['status']

    # Linux: Stopped
    @property
    def stopped(self) -> str:
        return self._table['stopped']

    # macOS: Tunnel
    @property
    def tunnel(self) -> str:
        return self._table['tunnel']

    # macOS: Tunnel mode
    @property
    def tunnel_mode(self) -> str:
        return self._table['tunnel_mode']

    # macOS: Unavailable
    @property
    def unavailable(self) -> str:
        return self._table['unavailable']

    # macOS: Unknown
    @property
    def unknown(self) -> str:
        return self._table['unknown']

    # macOS: Changes to a profile's text are not saved.
    @property
    def unsaved_changes_message(self) -> str:
        return self._table['unsaved_changes_message']

    # macOS: Uptime
    @property
    def uptime(self) -> str:
        return self._table['uptime']

    # macOS: Username
    @property
    def username(self) -> str:
        return self._table['username']

    # macOS: Warnings and errors
    @property
    def warnings_and_errors(self) -> str:
        return self._table['warnings_and_errors']

    # macOS: Wi-Fi
    @property
    def wi_fi(self) -> str:
        return self._table['wi_fi']
