#!/usr/bin/env python3
"""Regenerates src/plaitway/client/descriptor.binpb from proto/plaitway/v1/plaitway.proto.

The file is a serialized FileDescriptorSet, imports included. The client builds
its message classes from it at run time, because generated *_pb2.py modules
only work with the protobuf version they were generated by, and the app runs
on the grpcio and protobuf of the distribution.

Needs grpcio-tools (development only):  python tools/gen_descriptor.py [--check]
"""

import argparse
import os
import sys
import tempfile
from pathlib import Path

LINUX_DIR = Path(__file__).resolve().parent.parent
PROTO_DIR = LINUX_DIR.parent / "proto"
PROTO_FILE = "plaitway/v1/plaitway.proto"
OUTPUT = LINUX_DIR / "src" / "plaitway" / "client" / "descriptor.binpb"


def compile_descriptor(destination: Path) -> None:
    import grpc_tools
    from grpc_tools import protoc

    well_known = Path(grpc_tools.__file__).parent / "_proto"
    status = protoc.main([
        "protoc",
        f"-I{PROTO_DIR}",
        f"-I{well_known}",
        f"--descriptor_set_out={destination}",
        "--include_imports",
        PROTO_FILE,
    ])
    if status != 0:
        sys.exit(f"protoc failed with status {status}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when the committed file is stale")
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as scratch:
            fresh = Path(scratch) / "descriptor.binpb"
            compile_descriptor(fresh)
            if fresh.read_bytes() != OUTPUT.read_bytes():
                sys.exit(f"{OUTPUT} is stale: run tools/gen_descriptor.py")
        return
    compile_descriptor(OUTPUT)
    print(f"wrote {os.path.relpath(OUTPUT)}")


if __name__ == "__main__":
    main()
